# Generated by Django 4.2.5 on 2026-02-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='На сайте используется сервис веб-аналитики Яндекс Метрика с помощью технологий cookie для сбора и хранения данных, необходимых для корректной работы сайта и удобства посетителей. Продолжая пользоваться сайтом, вы соглашаетесь с использованием файлов cookie и политикой конфиденциальности персональных данных.', verbose_name='Текст сообщения')),
                ('policy_url', models.CharField(default='/custom/personal_data/', max_length=255, verbose_name='Ссылка на политику конфиденциальности')),
                ('hide_days', models.PositiveIntegerField(default=14, verbose_name='Скрывать на (дней)')),
            ],
            options={
                'verbose_name': 'Настройки cookie-уведомления',
                'verbose_name_plural': 'Настройки cookie-уведомления',
            },
        ),
    ]
