# Generated by Django 4.2.5 on 2023-09-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка на консультацию', 'verbose_name_plural': 'Заявки на консультацию'},
        ),
        migrations.AlterModelOptions(
            name='mainsliderimage',
            options={'verbose_name': 'Слайд с главной', 'verbose_name_plural': 'Слайды с главной'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место из географии ранней помощи', 'verbose_name_plural': 'Места из географии ранней помощи'},
        ),
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'verbose_name': 'Вопрос - ответ', 'verbose_name_plural': 'Вопросы - ответы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
