# Generated by Django 4.2.5 on 2023-10-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_questionanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='application',
            name='answered',
            field=models.BooleanField(default=False, verbose_name='Отвечено'),
        ),
        migrations.AddField(
            model_name='application',
            name='answering',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя ответившего'),
        ),
        migrations.AddField(
            model_name='mainsliderimage',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка при клике (необязательно)'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
    ]
