# Generated by Django 4.2.5 on 2023-10-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_application_answer_application_answered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='answered',
        ),
        migrations.AddField(
            model_name='application',
            name='treated',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='treated',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AddField(
            model_name='review',
            name='treated',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
    ]
