# Generated by Django 4.2.5 on 2023-11-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_banner_alter_mainsliderimage_image_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsliderimage',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Название'),
        ),
    ]
