# Generated by Django 4.2.5 on 2023-11-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_mainsliderimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='text',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
