# Generated by Django 4.2.5 on 2023-11-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_place_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
