# Generated by Django 4.2.5 on 2023-11-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_place_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда задан'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='treated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда обработан'),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Когда оставлен'),
        ),
        migrations.AddField(
            model_name='review',
            name='treated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда обработан'),
        ),
    ]
