# Generated by Django 4.2.5 on 2023-11-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_questionanswer_created_at_questionanswer_treated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('link', models.TextField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Ссылка с главной',
                'verbose_name_plural': 'Ссылки с главной',
            },
        ),
    ]
