# Generated by Django 4.2.5 on 2023-11-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_place_options_institution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Логотип министерств со ссылкой в подвале', 'verbose_name_plural': 'Логотипы министерств со ссылкой в подвале'},
        ),
        migrations.AlterModelOptions(
            name='indexlink',
            options={'verbose_name': 'Горячая ссылки', 'verbose_name_plural': 'Горячие ссылка'},
        ),
        migrations.AddField(
            model_name='indexlink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tmp/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='main.place', verbose_name='Город'),
        ),
    ]
