# Generated by Django 4.2.5 on 2023-11-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_indexlink_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsliderimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок вывода'),
        ),
        migrations.AddField(
            model_name='news',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок вывода'),
        ),
        migrations.AddField(
            model_name='place',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок вывода'),
        ),
    ]
