# Generated by Django 4.2.5 on 2023-12-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_mainsliderimage_order_news_order_place_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Город из географии ранней помощи', 'verbose_name_plural': 'Города из географии ранней помощи'},
        ),
        migrations.AlterField(
            model_name='institution',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
