# Generated by Django 4.2.5 on 2024-11-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыть в географии ранней помощи'),
        ),
    ]
