# Generated by Django 4.2.5 on 2025-02-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_place_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='category',
            field=models.CharField(choices=[('not_specified', 'Не задано'), ('social_development', 'Министерство социального развития, опеки и попечительства Иркутской области'), ('education', 'Министерство образования Иркутской области'), ('healthcare', 'Министерство здравоохранения Иркутской области'), ('non_profit', 'Социально-ориентированные некоммерческие организации Иркутской области')], default='not_specified', max_length=32, verbose_name='Категория'),
        ),
    ]
