# Generated by Django 4.2.5 on 2023-09-22 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает проверки'), ('approved', 'Одобрено'), ('declined', 'Отклонено')], max_length=32, verbose_name='Статус')),
                ('hidden', models.BooleanField(default=False, verbose_name='Статья скрыта')),
                ('theme', models.CharField(max_length=128, verbose_name='Тематика')),
                ('title', models.CharField(max_length=128, verbose_name='Название статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата написания')),
                ('approved_at', models.DateTimeField(null=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='specialists.article')),
            ],
        ),
    ]
