# Generated by Django 4.2.5 on 2023-09-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='articlefile',
            options={'verbose_name': 'Файл из статьи', 'verbose_name_plural': 'Файлы из статей'},
        ),
    ]
