# Generated by Django 4.2.5 on 2023-10-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0002_alter_article_options_alter_articlefile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleApprovalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('treated', models.BooleanField(default=False, verbose_name='Обработана')),
                ('response', models.BooleanField(default=False, verbose_name='Вердикт')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialists.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Заявка на публикацию статьи',
                'verbose_name_plural': 'Заявки на публикацию статьи',
            },
        ),
    ]
