# Generated by Django 4.2.5 on 2023-10-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0003_articleapprovalapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.AddField(
            model_name='article',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
    ]
