# Generated by Django 4.2.5 on 2023-10-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0004_remove_article_status_article_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
