# Generated by Django 4.2.5 on 2023-10-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0005_alter_article_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefile',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название (необязательно)'),
        ),
    ]
