# Generated by Django 4.2.5 on 2023-10-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0006_articlefile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='theme',
            field=models.TextField(verbose_name='Тематика'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='articleapprovalapplication',
            name='response',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
