# Generated by Django 4.2.5 on 2023-09-22 11:59

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=64, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('profession', models.CharField(max_length=64, verbose_name='Профессия')),
                ('photo', models.ImageField(upload_to='profile_photos/', verbose_name='Фото')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('birthdate', models.IntegerField(null=True, verbose_name='Дата рождения')),
                ('workplace_address', models.CharField(max_length=128, verbose_name='Адрес места работы')),
                ('workplace_name', models.CharField(max_length=128, verbose_name='Название места работы')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Номер рабочего телефона')),
                ('description', models.TextField(verbose_name='О себе')),
                ('registered', models.BooleanField(default=False, verbose_name='Реестровый специалист')),
                ('field_of_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.fieldofactivity', verbose_name='Сфера деятельности')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
