# Generated by Django 4.2.5 on 2023-09-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldofactivity',
            options={'verbose_name': 'Сфера деятельности', 'verbose_name_plural': 'Сферы деятельности'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
