# Generated by Django 4.2.5 on 2023-10-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_fieldofactivity_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
    ]
