# Generated by Django 4.2.5 on 2023-10-04 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен'),
        ),
        migrations.CreateModel(
            name='UserApprovalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('treated', models.BooleanField(default=False, verbose_name='Обработана')),
                ('response', models.BooleanField(default=False, verbose_name='Вердикт')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Заявка на одобрение профиля',
                'verbose_name_plural': 'Заявки на одобрение профиля',
            },
        ),
    ]
