# Generated by Django 4.2.5 on 2023-10-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_userapprovalapplication_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usereditapplication',
            options={'verbose_name': 'Заявка на изменение профиля', 'verbose_name_plural': 'Заявки на изменение профиля'},
        ),
        migrations.AddField(
            model_name='usereditapplication',
            name='verbose_field',
            field=models.CharField(max_length=32, null=True, verbose_name='Поле'),
        ),
    ]
