# Generated by Django 4.2.5 on 2023-10-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_usereditapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='tmp/', verbose_name='Фото'),
        ),
    ]
