# Generated by Django 4.2.5 on 2023-10-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=True, verbose_name='Почта подтверждена'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ключ подтверждения почты'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_key_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ключ истекает'),
        ),
    ]
