# Generated by Django 4.2.5 on 2023-11-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_email_verified_user_verification_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereditapplication',
            name='response',
            field=models.BooleanField(default=False, verbose_name='Одобрить'),
        ),
    ]
