# Generated by Django 4.2.5 on 2023-11-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_usereditapplication_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapprovalapplication',
            name='response',
            field=models.BooleanField(default=False, verbose_name='Одобрить'),
        ),
    ]
