# Generated by Django 4.2.5 on 2023-11-21 18:57

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_userapprovalapplication_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to=authentication.models.user_photo_upload, verbose_name='Фото'),
        ),
    ]
