# Generated by Django 4.2.5 on 2023-11-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_user_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Специалист ранней помощи', 'verbose_name_plural': 'Специалисты ранней помощи'},
        ),
    ]
