# Generated by Django 4.2.5 on 2023-11-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок вывода'),
        ),
    ]
