# Generated by Django 4.2.5 on 2024-01-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_user_profession_foauserconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='field_of_activity',
        ),
    ]
