# Generated by Django 4.2.5 on 2024-11-06 08:32

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_user_field_of_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.user_photo_upload, verbose_name='Фото'),
        ),
    ]
