# Generated by Django 4.2.5 on 2024-11-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия заявителя')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя заявителя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество заявителя')),
                ('relation', models.CharField(choices=[('parent', 'Родитель'), ('representative', 'Законный представитель'), ('other', 'Иное')], max_length=20, verbose_name='Степень родства')),
                ('relation_other', models.CharField(blank=True, max_length=200, null=True, verbose_name='Иное (уточнить)')),
                ('main_phone', models.CharField(max_length=20, verbose_name='Основной номер телефона')),
                ('additional_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Дополнительный номер телефона')),
                ('main_email', models.EmailField(max_length=254, verbose_name='Основной электронный адрес')),
                ('additional_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Дополнительный электронный адрес')),
                ('preferred_contact', models.JSONField(verbose_name='Предпочтительный способ связи')),
                ('preferred_time', models.CharField(choices=[('morning', 'с 10:00 до 13:00'), ('afternoon', 'с 14:00 до 17:00')], max_length=20, verbose_name='Удобное время для связи')),
                ('child_last_name', models.CharField(max_length=100, verbose_name='Фамилия ребенка')),
                ('child_first_name', models.CharField(max_length=100, verbose_name='Имя ребенка')),
                ('child_middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество ребенка')),
                ('child_birth_date', models.DateField(verbose_name='Дата рождения ребенка')),
                ('child_age_in_months', models.PositiveIntegerField(editable=False, verbose_name='Возраст ребенка в месяцах')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Улица/микрорайон')),
                ('house', models.CharField(max_length=20, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=20, null=True, verbose_name='Квартира')),
                ('reasons', models.JSONField(verbose_name='Причины обращения')),
                ('reason_other', models.CharField(blank=True, max_length=200, null=True, verbose_name='Иное (уточнить)')),
                ('referral_document', models.FileField(blank=True, null=True, upload_to='referrals/', verbose_name='Документ направления')),
                ('sources', models.JSONField(verbose_name='Источник информации')),
                ('source_other', models.CharField(blank=True, max_length=200, null=True, verbose_name='Иное (уточнить)')),
                ('consent', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('processed', 'Обработана'), ('feedback_received', 'Получена обратная связь')], default='new', max_length=20, verbose_name='Статус заявки')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], null=True, verbose_name='Оценка')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий администратора')),
                ('date_taken_in_work', models.DateField(blank=True, null=True, verbose_name='Дата взятия в работу')),
                ('date_processed', models.DateField(blank=True, null=True, verbose_name='Дата обработки')),
                ('date_feedback_received', models.DateField(blank=True, null=True, verbose_name='Дата получения обратной связи')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыта')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
    ]
