# Generated by Django 4.2.5 on 2024-11-09 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_place_is_hidden'),
        ('anketa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketa',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anketas', to='main.institution', verbose_name='Учреждение'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anketas', to='main.place', verbose_name='Город'),
        ),
    ]
