# Generated by Django 4.2.5 on 2024-11-10 04:10

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_user_photo'),
        ('anketa', '0002_anketa_institution_alter_anketa_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCRMUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_anketa_manager', models.BooleanField(default=False, verbose_name='Может работать с анкетами')),
                ('is_news_manager', models.BooleanField(default=False, verbose_name='Может работать с новостями')),
            ],
            options={
                'verbose_name': 'Пользователь CRM',
                'verbose_name_plural': 'Пользователи CRM',
            },
            bases=('authentication.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
