# Generated by Django 4.2.5 on 2024-11-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0004_anketa_responsible_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anketa',
            options={'verbose_name': 'Анкета (заявка на раннюю помощь)', 'verbose_name_plural': 'Анкеты (заявки на раннюю помощь)'},
        ),
        migrations.AlterField(
            model_name='anketa',
            name='created_at',
            field=models.DateTimeField(editable=False, verbose_name='Дата создания'),
        ),
    ]
