# Generated by Django 4.2.5 on 2024-12-10 09:56

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_place_is_hidden'),
        ('anketa', '0005_alter_anketa_options_alter_anketa_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='institution',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='city', chained_model_field='place', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.institution', verbose_name='Учреждение'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('processed', 'Обработана'), ('feedback_received', 'Оценена')], default='new', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
