# Generated by Django 4.2.5 on 2024-12-10 10:06

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_place_is_hidden'),
        ('anketa', '0006_alter_anketa_institution_alter_anketa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketa',
            name='region_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anketas_by_region', to='main.place', verbose_name='Регион учреждения'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='institution',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='city', chained_model_field='place', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anketas', to='main.institution', verbose_name='Учреждение'),
        ),
    ]
