# Generated by Django 4.2.5 on 2023-09-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='FileSetBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название раздела')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='Заголовок страницы')),
                ('url', models.CharField(max_length=16, unique=True, verbose_name='URL страницы (перевод заголовка на английский, в нижнем регистре, с _ вместо пробелов)')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('approved', models.BooleanField(default=False, verbose_name='Публичный доступ')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='custom.section', verbose_name='Раздел меню (оставьте незаполненным, если страница не является подразделом)')),
            ],
        ),
        migrations.CreateModel(
            name='FileSetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название (необязательно)')),
                ('file_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='custom.filesetblock', verbose_name='Набор файлов')),
            ],
        ),
        migrations.AddField(
            model_name='filesetblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.page', verbose_name='Страница'),
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название (необязательно)')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='custom.albumblock', verbose_name='Альбом')),
            ],
        ),
        migrations.AddField(
            model_name='albumblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom.page', verbose_name='Страница'),
        ),
    ]
