# Generated by Django 4.2.5 on 2023-10-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_alter_albumblock_options_alter_albumimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=16, unique=True, verbose_name='URL страницы (заполняется автоматически)'),
        ),
    ]
