# Generated by Django 4.2.5 on 2023-10-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_alter_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=models.ImageField(upload_to='tmp/', verbose_name='Изображение'),
        ),
    ]
