# Generated by Django 4.2.5 on 2023-10-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0005_alter_albumimage_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesetfile',
            name='file_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='custom.filesetblock', verbose_name='Набор файлов'),
        ),
    ]
