# Generated by Django 4.2.5 on 2023-11-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0006_alter_filesetfile_file_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Заголовок страницы'),
        ),
    ]
