# Generated by Django 4.2.5 on 2023-11-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0007_alter_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Порядок'),
        ),
    ]
