# Generated by Django 4.2.5 on 2023-12-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0008_section_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name='URL страницы (заполняется автоматически)'),
        ),
    ]
