# Generated by Django 4.2.5 on 2024-08-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0010_alter_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Порядок'),
        ),
    ]
