# Generated by Django 4.2.5 on 2024-11-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0011_page_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
