# Generated by Django 4.2.5 on 2026-09-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0012_alter_page_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='ФИО')),
                ('profession', models.CharField(max_length=128, verbose_name='Специальность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tmp/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сотрудник коллектива',
                'verbose_name_plural': 'Коллектив',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
